# Generated by Django 6.0.6 on 2026-06-26 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='upadted',
            new_name='updated',
        ),
    ]
